name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
       - uses: actions/checkout@v1
       - name: Install & Tests
         run: |
           npm install
           npm test
           
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
        env: 
            username: "adrianaab"
            password: "A.arias2022"
      - name: Docker login 
        run: docker login -u "$USERNAME" -p "$PASSWORD"
        
      - run: echo "${{ vars.DOCKER_USER }}"
      
      - name: Build
        run: docker build --no-cache --progress=plain -t back .
        
      - name: Tags
        run: |
            docker tag back "$USERNAME"/back:${{ github.sha }}
            docker tag back "$USERNAME"/back:latest

      - name: Push
        run: | 
            docker push "$USERNAME"/back:${{ github.sha }}
            docker push "$USERNAME"/back:latest
            
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "variable from shell environment : $env_var"

    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
