name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
       - uses: actions/checkout@v1
       - name: Install & Tests
         run: |
           npm install
           npm test
           
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: 'index.docker.io' 
          username: 'adrianaab'
          password: 'A.arias2022'
        
      - name: Build
        run: docker build --no-cache --progress=plain -t back .
        
      - name: Tags
        run: |
            docker tag back adrianaab/back:${{ github.sha }}
            docker tag back adrianaab/back:latest

      - name: Push
        run: | 
            docker push adrianaab/back:${{ github.sha }}
            docker push adrianaab/back:latest

