name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
       - uses: actions/checkout@v1
       - name: Install & Tests
         run: |
           npm install
           npm test
           
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
        with: 
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker login 
        run: docker login -u $USERNAME -p $PASSWORD 
        
      - name: Build
        run: docker build --no-cache --progress=plain -t back .
        
      - name: Tags
        run: |
            docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
            docker tag back ${{ secrets.DOCKER_USER }}/back:latest

      - name: Push
        run: | 
            docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USER }}/back:latest

